#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greg.Xrm.Mcp.FormEngineer.Model
{
	
	
	/// <summary>
	/// Select the navigation type of the app.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum appmodule_navigationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Singlesession = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Multisession = 1,
	}
	
	/// <summary>
	/// Status of the Model-driven App
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum appmodule_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Model-driven App
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum appmodule_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 3,
	}
	
	/// <summary>
	/// A role-based, modular business app that provides task-based functionality for a particular area of work.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("appmodule")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public partial class AppModule : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public AppModule() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "appmodule";
		
		public const string EntityLogicalCollectionName = "appmodules";
		
		public const string EntitySetName = "appmodules";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// This field is used to store AI generated Description for Model-driven App
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aiappdescription")]
		public string aiappdescription
		{
			get
			{
				return this.GetAttributeValue<string>("aiappdescription");
			}
			set
			{
				this.OnPropertyChanging("aiappdescription");
				this.SetAttributeValue("aiappdescription", value);
				this.OnPropertyChanged("aiappdescription");
			}
		}
		
		/// <summary>
		/// This field stores the Time when last AI App Description was generated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aidescriptiongeneratedon")]
		public System.Nullable<System.DateTime> aidescriptiongeneratedon
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aidescriptiongeneratedon");
			}
			set
			{
				this.OnPropertyChanging("aidescriptiongeneratedon");
				this.SetAttributeValue("aidescriptiongeneratedon", value);
				this.OnPropertyChanged("aidescriptiongeneratedon");
			}
		}
		
		/// <summary>
		/// This field is used to store App Graph for Model-driven App
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appgraph")]
		public string appgraph
		{
			get
			{
				return this.GetAttributeValue<string>("appgraph");
			}
			set
			{
				this.OnPropertyChanging("appgraph");
				this.SetAttributeValue("appgraph", value);
				this.OnPropertyChanged("appgraph");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmoduleid")]
		public System.Nullable<System.Guid> AppModuleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("appmoduleid");
			}
			set
			{
				this.OnPropertyChanging("AppModuleId");
				this.SetAttributeValue("appmoduleid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("AppModuleId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmoduleid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.AppModuleId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the App Module used when synchronizing customizations for the Microsoft Dynamics 365 client for Outlook
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmoduleidunique")]
		public System.Nullable<System.Guid> AppModuleIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("appmoduleidunique");
			}
			set
			{
				this.OnPropertyChanging("AppModuleIdUnique");
				this.SetAttributeValue("appmoduleidunique", value);
				this.OnPropertyChanged("AppModuleIdUnique");
			}
		}
		
		/// <summary>
		/// App Module Version
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmoduleversion")]
		public string AppModuleVersion
		{
			get
			{
				return this.GetAttributeValue<string>("appmoduleversion");
			}
			set
			{
				this.OnPropertyChanging("AppModuleVersion");
				this.SetAttributeValue("appmoduleversion", value);
				this.OnPropertyChanged("AppModuleVersion");
			}
		}
		
		/// <summary>
		/// App Module Xml Managed
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmodulexmlmanaged")]
		public string AppModuleXmlManaged
		{
			get
			{
				return this.GetAttributeValue<string>("appmodulexmlmanaged");
			}
			set
			{
				this.OnPropertyChanging("AppModuleXmlManaged");
				this.SetAttributeValue("appmodulexmlmanaged", value);
				this.OnPropertyChanged("AppModuleXmlManaged");
			}
		}
		
		/// <summary>
		/// Client Type such as Web or UCI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clienttype")]
		public System.Nullable<int> ClientType
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("clienttype");
			}
			set
			{
				this.OnPropertyChanging("ClientType");
				this.SetAttributeValue("clienttype", value);
				this.OnPropertyChanged("ClientType");
			}
		}
		
		/// <summary>
		/// For internal use only
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Contains configuration XML
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("configxml")]
		public string ConfigXML
		{
			get
			{
				return this.GetAttributeValue<string>("configxml");
			}
			set
			{
				this.OnPropertyChanging("ConfigXML");
				this.SetAttributeValue("configxml", value);
				this.OnPropertyChanged("ConfigXML");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Description for entity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// App Module Descriptor
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("descriptor")]
		public string Descriptor
		{
			get
			{
				return this.GetAttributeValue<string>("descriptor");
			}
		}
		
		/// <summary>
		/// App Module Event Handlers
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eventhandlers")]
		public string EventHandlers
		{
			get
			{
				return this.GetAttributeValue<string>("eventhandlers");
			}
			set
			{
				this.OnPropertyChanging("EventHandlers");
				this.SetAttributeValue("eventhandlers", value);
				this.OnPropertyChanged("EventHandlers");
			}
		}
		
		/// <summary>
		/// Form Factor
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("formfactor")]
		public System.Nullable<int> FormFactor
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("formfactor");
			}
			set
			{
				this.OnPropertyChanging("FormFactor");
				this.SetAttributeValue("formfactor", value);
				this.OnPropertyChanged("FormFactor");
			}
		}
		
		/// <summary>
		/// Unique identifier of the data import or data migration that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Version in which the similarity rule is introduced.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("introducedversion")]
		public string IntroducedVersion
		{
			get
			{
				return this.GetAttributeValue<string>("introducedversion");
			}
			set
			{
				this.OnPropertyChanging("IntroducedVersion");
				this.SetAttributeValue("introducedversion", value);
				this.OnPropertyChanged("IntroducedVersion");
			}
		}
		
		/// <summary>
		/// Is Default
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdefault")]
		public System.Nullable<bool> IsDefault
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdefault");
			}
			set
			{
				this.OnPropertyChanging("IsDefault");
				this.SetAttributeValue("isdefault", value);
				this.OnPropertyChanged("IsDefault");
			}
		}
		
		/// <summary>
		/// Is Featured
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isfeatured")]
		public System.Nullable<bool> IsFeatured
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isfeatured");
			}
			set
			{
				this.OnPropertyChanging("IsFeatured");
				this.SetAttributeValue("isfeatured", value);
				this.OnPropertyChanged("IsFeatured");
			}
		}
		
		/// <summary>
		/// Is Managed
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Name of App Module
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// App navigation type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("navigationtype")]
		public virtual appmodule_navigationtype? NavigationType
		{
			get
			{
				return ((appmodule_navigationtype?)(EntityOptionSetEnum.GetEnum(this, "navigationtype")));
			}
			set
			{
				this.OnPropertyChanging("NavigationType");
				this.SetAttributeValue("navigationtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("NavigationType");
			}
		}
		
		/// <summary>
		/// The client that this app is optimized for
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("optimizedfor")]
		public string OptimizedFor
		{
			get
			{
				return this.GetAttributeValue<string>("optimizedfor");
			}
			set
			{
				this.OnPropertyChanging("OptimizedFor");
				this.SetAttributeValue("optimizedfor", value);
				this.OnPropertyChanged("OptimizedFor");
			}
		}
		
		/// <summary>
		/// Unique identifier of the organization associated with the app.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Internal use only
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Date and time when the record was published.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("publishedon")]
		public System.Nullable<System.DateTime> PublishedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("publishedon");
			}
			set
			{
				this.OnPropertyChanging("PublishedOn");
				this.SetAttributeValue("publishedon", value);
				this.OnPropertyChanged("PublishedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the publisher.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("publisherid")]
		public Microsoft.Xrm.Sdk.EntityReference PublisherId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("publisherid");
			}
			set
			{
				this.OnPropertyChanging("PublisherId");
				this.SetAttributeValue("publisherid", value);
				this.OnPropertyChanged("PublisherId");
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Status of the Model-driven App
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual appmodule_statecode? statecode
		{
			get
			{
				return ((appmodule_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Model-driven App
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual appmodule_statuscode? statuscode
		{
			get
			{
				return ((appmodule_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// Unique Name of App Module
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniquename")]
		public string UniqueName
		{
			get
			{
				return this.GetAttributeValue<string>("uniquename");
			}
			set
			{
				this.OnPropertyChanging("UniqueName");
				this.SetAttributeValue("uniquename", value);
				this.OnPropertyChanged("UniqueName");
			}
		}
		
		/// <summary>
		/// Contains URL
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("url")]
		public string URL
		{
			get
			{
				return this.GetAttributeValue<string>("url");
			}
			set
			{
				this.OnPropertyChanging("URL");
				this.SetAttributeValue("url", value);
				this.OnPropertyChanged("URL");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the Web Resource
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("webresourceid")]
		public System.Nullable<System.Guid> WebResourceId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("webresourceid");
			}
			set
			{
				this.OnPropertyChanging("WebResourceId");
				this.SetAttributeValue("webresourceid", value);
				this.OnPropertyChanged("WebResourceId");
			}
		}
		
		/// <summary>
		/// Unique identifier of the Web Resource as Welcome Page Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("welcomepageid")]
		public System.Nullable<System.Guid> WelcomePageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("welcomepageid");
			}
			set
			{
				this.OnPropertyChanging("WelcomePageId");
				this.SetAttributeValue("welcomepageid", value);
				this.OnPropertyChanged("WelcomePageId");
			}
		}
		
		/// <summary>
		/// 1:N appmodule_appmodulecomponent
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appmodule_appmodulecomponent")]
		public System.Collections.Generic.IEnumerable<Greg.Xrm.Mcp.FormEngineer.Model.AppModuleComponent> appmodule_appmodulecomponent
		{
			get
			{
				return this.GetRelatedEntities<Greg.Xrm.Mcp.FormEngineer.Model.AppModuleComponent>("appmodule_appmodulecomponent", null);
			}
			set
			{
				this.OnPropertyChanging("appmodule_appmodulecomponent");
				this.SetRelatedEntities<Greg.Xrm.Mcp.FormEngineer.Model.AppModuleComponent>("appmodule_appmodulecomponent", null, value);
				this.OnPropertyChanged("appmodule_appmodulecomponent");
			}
		}
	}
}
#pragma warning restore CS1591
