#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greg.Xrm.Mcp.FormEngineer.Model
{
	
	
	/// <summary>
	/// XML data used to control the application navigation pane.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("sitemap")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public partial class SiteMap : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public SiteMap() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "sitemap";
		
		public const string EntityLogicalCollectionName = "sitemaps";
		
		public const string EntitySetName = "sitemaps";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Shows who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalfÂ of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Enable to allow sitemap groups to be collapsed.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("enablecollapsiblegroups")]
		public System.Nullable<bool> EnableCollapsibleGroups
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("enablecollapsiblegroups");
			}
			set
			{
				this.OnPropertyChanging("EnableCollapsibleGroups");
				this.SetAttributeValue("enablecollapsiblegroups", value);
				this.OnPropertyChanged("EnableCollapsibleGroups");
			}
		}
		
		/// <summary>
		/// Information about whether the site map is associated with app module.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isappaware")]
		public System.Nullable<bool> IsAppAware
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isappaware");
			}
			set
			{
				this.OnPropertyChanging("IsAppAware");
				this.SetAttributeValue("isappaware", value);
				this.OnPropertyChanged("IsAppAware");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Enable to show the home button in the sitemap.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("showhome")]
		public System.Nullable<bool> ShowHome
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("showhome");
			}
			set
			{
				this.OnPropertyChanging("ShowHome");
				this.SetAttributeValue("showhome", value);
				this.OnPropertyChanged("ShowHome");
			}
		}
		
		/// <summary>
		/// Enable to show the pinned dropdown in the sitemap.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("showpinned")]
		public System.Nullable<bool> ShowPinned
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("showpinned");
			}
			set
			{
				this.OnPropertyChanging("ShowPinned");
				this.SetAttributeValue("showpinned", value);
				this.OnPropertyChanged("ShowPinned");
			}
		}
		
		/// <summary>
		/// Enable to show the recents dropdown in the sitemap.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("showrecents")]
		public System.Nullable<bool> ShowRecents
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("showrecents");
			}
			set
			{
				this.OnPropertyChanging("ShowRecents");
				this.SetAttributeValue("showrecents", value);
				this.OnPropertyChanged("ShowRecents");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sitemapid")]
		public System.Nullable<System.Guid> SiteMapId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("sitemapid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sitemapid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				base.Id = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sitemapidunique")]
		public System.Nullable<System.Guid> SiteMapIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("sitemapidunique");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sitemapname")]
		public string SiteMapName
		{
			get
			{
				return this.GetAttributeValue<string>("sitemapname");
			}
			set
			{
				this.OnPropertyChanging("SiteMapName");
				this.SetAttributeValue("sitemapname", value);
				this.OnPropertyChanged("SiteMapName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sitemapnameunique")]
		public string SiteMapNameUnique
		{
			get
			{
				return this.GetAttributeValue<string>("sitemapnameunique");
			}
			set
			{
				this.OnPropertyChanging("SiteMapNameUnique");
				this.SetAttributeValue("sitemapnameunique", value);
				this.OnPropertyChanged("SiteMapNameUnique");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sitemapxml")]
		public string SiteMapXml
		{
			get
			{
				return this.GetAttributeValue<string>("sitemapxml");
			}
			set
			{
				this.OnPropertyChanging("SiteMapXml");
				this.SetAttributeValue("sitemapxml", value);
				this.OnPropertyChanged("SiteMapXml");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sitemapxmlmanaged")]
		public string SiteMapXmlManaged
		{
			get
			{
				return this.GetAttributeValue<string>("sitemapxmlmanaged");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
	}
}
#pragma warning restore CS1591
