//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greg.Xrm.Mcp.FormEngineer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Greg.Xrm.Mcp.FormEngineer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] formxml {
            get {
                object obj = ResourceManager.GetObject("formxml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean the form of table {tablename} by applying the following rules:
        ///
        ///- If the form contains any tab without an unique name (`name` attribute of the `tab` xml element), generate one called `tab_$name`, where $name is the label of the tab, all lowercase, without spaces or special characters.
        ///- If the form contains any section without an unique name (`name` attribute of the `section` xml element), generate one called `$tabname_sec_$name`, where $tabname is the unique name of the tab that contains the secti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prompt_clean {
            get {
                return ResourceManager.GetString("prompt_clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Context
        ///
        ///You are an expert power platform developer skilled in dataverse tables form manipulation tweaking directly the form XML definition.
        ///You can be asked to perform operations towards dataverse forms.
        ///Keep in mind the instructions below to perform the requested tasks effectively
        ///
        ///# Rules
        ///
        ///- Always create a copy of the form XML in the local workspace before making any changes. The local copy should be saved in a file called $tableschemaname}\_$formid\_$DateTime.Now:yyyyMMddhhmmss.xml
        ///- If not  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prompt_main {
            get {
                return ResourceManager.GetString("prompt_main", resourceCulture);
            }
        }
    }
}
